### ISSUE TITLE
403 Forbidden thrown even though correct username and password are correct

### ISSUE THREAD

**Issue by jleaders** [ototadana/JenkinsOnDesktop#8]
I double checked the username and password but it still gives 403 Forbidden... Tested on Jenkins ver. 1.636

See below:

     System.ApplicationException: Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (403) Forbidden."
      At line:1 char:51
      + ...  .\main.ps1;Main http://leadersandcompany.us.to:7020/ -user DesertSha ...
      +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

         at XPFriend.JenkinsOnDesktop.Core.ScriptEngine.ScriptEngineBase.GetObject[T](PowerShell powerShell, Collection`1 psobjects)
         at XPFriend.JenkinsOnDesktop.Core.Business.CreateReport(Hashtable report)
         at XPFriend.JenkinsOnDesktop.Core.Workspace.DoBusiness()
         at XPFriend.JenkinsOnDesktop.MainWindow.DoBusinessAndUpdateWindow(Object sender, EventArgs e)
         at System.Windows.Media.Animation.Clock.FireEvent(EventPrivateKey key)
         at System.Windows.Media.Animation.Clock.RaiseAccumulatedEvents()
         at System.Windows.Media.Animation.TimeManager.RaiseEnqueuedEvents()
         at System.Windows.Media.Animation.TimeManager.Tick()
         at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
         at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
         at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
         at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jleaders** [comment]
I can confirm this is caused by the latest version of Jenkins not using Auth Challenges.
In other words, if you run:

    wget http://leadersandcompany.us.to:7020/cc.xml

It will fail. And if you run 

    wget http://leadersandcompany.us.to:7020/cc.xml --user=SOMEUSER --password=SOMEPASS

it will also fail. BUT if you run the following, it will succeed:

    wget http://leadersandcompany.us.to:7020/cc.xml --user=SOMEUSER --password=SOMEPASS --no-auth-challenge

Therefore in the meantime I am using CCTray & csnate/cctray-jenkins-transport which support authentication propery

**Comment by ototadana** [comment]
Thank you for good information!

You may fix the problem by the following steps:

1.  Click **Show Configuration...**
2.  Click **Business** tab
3.  Click **Open Configuration Folder**
4.  Open **main.ps1** with text editor
5.  Replace the lines:
    ```powershell
    if(![System.String]::IsNullOrEmpty($user)) {
        $credential = New-Object System.Net.NetworkCredential($user, $password);
    }
    $client.Credentials = $credential
   ```

    with

    ```powershell
    if(![System.String]::IsNullOrEmpty($user)) {
        $authInfo = [System.Convert]::ToBase64String([System.Text.Encoding]::Default.GetBytes($user + ":" + $password))
        $client.Headers.Add("Authorization", "Basic " + $authInfo)
    }
    ```

**Comment by kradikar** [comment]
I am getting same issue now. I'm using Jenkins 2.46.2 and I get the error. Kindly note that the entire setup is fresh(Jenkins server and Jenkins on Desktop).
I checked the main.ps1 script and it has new script mentioned above.
Exception log:
Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (403) Forbidden."
At line:1 char:51
+ ... $report = $i};. .\main.ps1;Main https://localhost:8080
+                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   at XPFriend.JenkinsOnDesktop.Core.ScriptEngine.ScriptEngineBase.GetObject[T](PowerShell powerShell, Collection`1 psobjects) in C:\Users\Admin\Downloads\Jenkins\JenkinsOnDesktop-master\JenkinsOnDesktop\Core\ScriptEngine\ScriptEngineBase.cs:line 37
   at XPFriend.JenkinsOnDesktop.Core.ScriptEngine.BusinessScriptEngine.ExecuteScript(String businessName, String parameters, Hashtable report) in C:\Users\Admin\Downloads\Jenkins\JenkinsOnDesktop-master\JenkinsOnDesktop\Core\ScriptEngine\BusinessScriptEngine.cs:line 25
   at XPFriend.JenkinsOnDesktop.Core.ScriptEngine.BusinessScriptEngine.Execute(String businessName, String parameters, Hashtable report) in C:\Users\Admin\Downloads\Jenkins\JenkinsOnDesktop-master\JenkinsOnDesktop\Core\ScriptEngine\BusinessScriptEngine.cs:line 16
   at XPFriend.JenkinsOnDesktop.Core.Business.CreateReport(Hashtable report) in C:\Users\Admin\Downloads\Jenkins\JenkinsOnDesktop-master\JenkinsOnDesktop\Core\Business.cs:line 32
   at XPFriend.JenkinsOnDesktop.Core.Workspace.DoBusiness() in C:\Users\Admin\Downloads\Jenkins\JenkinsOnDesktop-master\JenkinsOnDesktop\Core\Workspace.cs:line 37
   at XPFriend.JenkinsOnDesktop.MainWindow.DoBusinessAndUpdateWindow(Object sender, EventArgs e) in C:\Users\Admin\Downloads\Jenkins\JenkinsOnDesktop-master\JenkinsOnDesktop\MainWindow.xaml.cs:line 232
   at System.Windows.Media.Animation.Clock.FireEvent(EventPrivateKey key)
   at System.Windows.Media.Animation.Clock.RaiseAccumulatedEvents()
   at System.Windows.Media.Animation.TimeManager.RaiseEnqueuedEvents()
   at System.Windows.Media.Animation.TimeManager.Tick()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
